package cn.nit.beauty.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table CATEGORY.
 */
public class Category implements Serializable{

    private Long id;
    /** Not-null value. */
    private String CATEGORY;
    private Integer CATEGORY_ICON;
    private Integer ICON;
    /** Not-null value. */
    private String TITLE;
    private String URL;
    private Boolean CHOICE = false;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String CATEGORY, Integer CATEGORY_ICON, Integer ICON, String TITLE, String URL, Boolean CHOICE) {
        this.id = id;
        this.CATEGORY = CATEGORY;
        this.CATEGORY_ICON = CATEGORY_ICON;
        this.ICON = ICON;
        this.TITLE = TITLE;
        this.URL = URL;
        this.CHOICE = CHOICE;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCATEGORY() {
        return CATEGORY;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCATEGORY(String CATEGORY) {
        this.CATEGORY = CATEGORY;
    }

    public Integer getCATEGORY_ICON() {
        return CATEGORY_ICON;
    }

    public void setCATEGORY_ICON(Integer CATEGORY_ICON) {
        this.CATEGORY_ICON = CATEGORY_ICON;
    }

    public Integer getICON() {
        return ICON;
    }

    public void setICON(Integer ICON) {
        this.ICON = ICON;
    }

    /** Not-null value. */
    public String getTITLE() {
        return TITLE;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE;
    }

    public String getURL() {
        return URL;
    }

    public void setURL(String URL) {
        this.URL = URL;
    }

    public Boolean getCHOICE() {
        return CHOICE;
    }

    public void setCHOICE(Boolean CHOICE) {
        this.CHOICE = CHOICE;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Category category = (Category) o;

        if (id != null ? !id.equals(category.id) : category.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
